### PR TITLE
Code reduction

### PR DESCRIPTION
**Pull request by lxgr-linux**
Hello,
I removed your massive if statement in favour of an giant array, I added the ability to exit your script via ctrl-c and I made it executable, so that it can be executed without the python3 prefix.
Greetings

### CODE REVIEW

**Comment by voider755** [comment]
Hi, thank you. I just merged and now I'm trying your changes. Ctrl+c exits, the commands seem to perform OK, ./almh launches it now without the python prefix, but now after any number input it prints a number sequence, like you input "3" and it prints just before output:
3
2
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12]
I'm checking now, but you could check it too and see what happens. Thanks again!

**Comment by voider755** [comment]
I've put the original code back and opened an issue. If this can't be solved, I'll add the executable and the Ctrl+c exit anyway, but not the array, and will keep the if statements. I know it's longer (as in more lines), but we're talking 90 LOC. :)

**Comment by lxgr-linux** [comment]
The problem accured because of the lines 50/51 of my commit, which where just print statements I used for debugging I forgot to remove.

**Comment by voider755** [comment]
I've added the made-executable and the Crtl+c to exit from your pull request, and made some changes in the code (added new sub-option to install after perform a search and some other minor changes) in the meanwhile. I'm not sure of the change-if-into-array strategy anyway. Yes, it's way shorter (in LOC at least) but as of now it executes fast as hell anyway, and the code is very straightforward to hack. Any benefits from the array I'm not seeing? Thanks! :)

**Comment by lxgr-linux** [comment]
I just wanted to explain what went wrong with my commit. I think your method is the most suitable for your use case, especially with your added options.

**Comment by voider755** [comment]
Cool. Anyway, some bits of your contribution have been merged, for which you've been credited in the README (section "CHANGES"). I have some more options in mind, related to systemd/log checks and stuff, system info, etc., but that would imply offer a global menu first and then submenus; less fast, less straightforward maybe then. I'll let it as it is now and maybe I'll fork an "advanced" version, maybe with ncurses or else. Once more, thank you! :)

**Pull request merged**
